### ISSUE TITLE
Make an embedable widget to help with adoption & contributions

### ISSUE THREAD

**Issue by nczhu** [enabledao/enable#103]
Inspiration: https://www.buymeacoffee.com/

How it might work: 
- every campaign generates an embeddable widget
- people can click on widget to go to the contributions page

Rationale: 
I think a huge part of the UX is to enable fund recipients to growth hack their own campaigns. This is of course, not the only manifestation of that idea.

**Comment by Trumpcite** [comment]
https://github.com/enabledao/enable/projects/1#card-27784840
