### ISSUE TITLE
User testing www.ines.fund

### ISSUE THREAD

**Issue by wimanesti** [enabledao/enable#107]
www.ines.fund is being built and in user-testing stage. Need at least 10 feedback from blockchain community to improve the web in terms of layout, design and flow.

**Comment by onggunhao** [comment]
@wimanesti I think we should make this task most descriptive. 

Can you search for user testing specs online? Ideally, you want to 

1. Explain what the product is, 
2. Outline the scenario (give the user a Goal to achieve)
3. Ask guiding questions (e.g. did you find X confusing?)

**Comment by vs77bb** [comment]
@onggunhao @wimanesti Let me know when this is ready for bounty 🙂

**Comment by wimanesti** [comment]
User testing feedback:
[Katie.docx](https://github.com/enabledao/enable/files/3388381/Katie.docx)
[Anita - CX Manager.docx](https://github.com/enabledao/enable/files/3388382/Anita.-.CX.Manager.docx)
[Anthony Thio.docx](https://github.com/enabledao/enable/files/3388383/Anthony.Thio.docx)

**Comment by onggunhao** [comment]
@vs77bb We discussed it during UI standup today

* @urmauur will make changes to the UI in response to feedback from Katie, Anita and Anthony
* @wimanesti will create a UI test plan and instructions for user testers
