### ISSUE TITLE
Lenders should be able to view loan request and amortization schedule and buy fractional shares of loan request

### ISSUE THREAD

**Issue by onggunhao** [enabledao/enable#11]
**Step 3: Lenders can view Loan Request and amortization schedule**
Once Loan Contract (at the stage of 'new request') has been deployed, lenders should be able to view the loan request on a frontend app. The frontend app should show the loan parameters that the borrower requested. The frontend app should also show the amortization schedule (i.e. repayment table). The frontend app _might_ also show some graphs to show the declining outstanding balance.

**Step 4: Lenders can fund the loan request**
_[Needs more thought]_ Lender should be able to either:

* Buy fractional shares of the loan (e.g. 1000 outstanding shares) - this might be easier for routing repayments
* Contribute variable amount, as long as it is within the loan cap

For simplicity, Lender should use a stablecoin (e.g. Dai). However, given that Dai is currently trading at 0.95, we might explore fiat-collateralized stablecoins (e.g. Paxos, USDC) as an interim measure.

### To dos:
- [ ] Wireframes for Lender page and viewing amortization table @onggunhao 
- [ ] Use ERC-20 contract to interface with Dharma debt contract?

**Comment by tspoff** [comment]
* Potential lenders will be able to buy shares by interacting with a smart contract via the web app
* You can view the loan parameters from the chain and put them in a nice format in the web app

**Comment by adibas03** [comment]
To use fractional shares,
somthing in the lines of this should suffice @tspoff  
```

Loan {
...
uint blockSize
}

constructor(
        ...
        uint _blockSize,
        ...
    ) ...{
    ...
    loan.blockSize = _blockSize;
    ...
}

function getEffectiveValue(amount) internal returns (uint){
    if (loan.blockSize === 0) {
        return amount;
    } else {
        return (amount/loan.blockSize) * loan.blockSize;
    }
}

function buyTokens(address beneficiary, uint amount) public nonReentrant {
   amount = getEffectiveValue(amount);
   ...
}
```

**Comment by onggunhao** [comment]
Superseded by debt token
