### ISSUE TITLE
Think of way to do proof-of-"social attestation"

### ISSUE THREAD

**Issue by onggunhao** [enabledao/enable#2]
### Initial thoughts

* Can we use existing tools (e.g. 3Box or uPort) to verify social media profiles of borrowers and attestors?

* If we do it from scratch, can we use the LinkedIn OAuth flow to get users' token and verify ownership of LinkedIn account?

* Loan Contract needs method to allow another wallet (hopefully w/ 3Box or uPort) to attest 

* Is there a better name for social attestation? Gah

**Comment by tspoff** [comment]
**Existing Blockchain ID**
Leveraging 3Box or uPort makes sense.

**Existing Social Repuation Options**
Is there an existing trusted provider of social reputation? If so, we could potentially use oracles to get this data in and associate it with ethereum addresses.

**Reputation System Thoughts**
Users generate social reputation somehow. Perhaps they can get their credit score on-chain in the oracle fashion. 

'Reptuation points' could be 'staked' onto others loan requests and burned if they default.

**Comment by onggunhao** [comment]
@tspoff

For social reputation options, would we consider LinkedIn? (e.g. associating Ethereum address with LinkedIn profile)

For reputation system, could there be a "proof of work" type task they do (eg learn JavaScript) that demonstrates ability to learn and determination?

**Comment by onggunhao** [comment]
Closing as we have decided to implement 3Box for the MVP iteration
