### ISSUE TITLE
Ethereum-based data reading 

### ISSUE THREAD

**Issue by tspoff** [enabledao/enable#24]
The simplest approaches are web3 subscriptions in front end, and TheGraph. 
I imagine we'll eventually want a service that handles making queries to data sources for each of our integrations.

### Simple Social Staking (our code)
Simple web3 subscription in front-end and filtered events should be fine here

### Bloom
However, the Bloom attestation events don't use indexed parameters  😬 
They do have good event coverage, TheGraph would work

### Crowdloan (our code)
We can design it to have good event coverage.

**Comment by onggunhao** [comment]
@tspoff TheGraph would be great for this

**Comment by onggunhao** [comment]
Moved to enable-ui repo https://github.com/enabledao/enable-ui/issues/8
