### ISSUE TITLE
Can we use an existing loan contract?

### ISSUE THREAD

**Issue by tspoff** [enabledao/enable#65]
**Dharma**
It will add unnecessary complexity for the loan process and will still require custom code for the crowdfunding aspect. We can certainly take architectural inspiration.

**Compound**

**Comment by onggunhao** [comment]
I'll be closing the old issue (#4) and replicating the discussion here:

- [ ] [Lendingblock Loan Contracts](https://github.com/lendingblock/loan-contracts)
- [ ] [Basic Ethereum Crowdsale contract](https://www.ethereum.org/crowdsale)
- [ ] [Blockchain-based P2P Loan using Neural Networks](https://github.com/bhaumik-choksi/Loan)
- [ ] [Weilend](https://github.com/frozeman/ethereum-smart-contracts/blob/master/p2plending/WeiLend.sol)
- [ ] [Loan Hack](https://github.com/HumanDynamics/loan-hack)
- [ ] [Open Law Contracts](https://media.consensys.net/openlaw-and-the-loan-syndications-and-trading-association-partner-to-automate-complex-loan-ed2b2bf85b8b)

**Comment by tspoff** [comment]
I've been revisiting Dharma, I now feel that it might be the way to go now that we're unconstrained by the hackathon timeframe. I was working on it in the dharma-loans branch yesterday.

Thoughts in no particular order:
* It's a familiar interface and known brand for potential lenders
* It does most of what we need, including repayment process
* We could have loan repayments and terms more easily tracked on sites that do that
* We don't have to use or create a relayer - we can have that info on-chain if we want
* The crowdloan contract would submit the debt order once sufficiently filled, and own the debt token

**Comment by onggunhao** [comment]
Closing issue as we have made the decision to build our own loan contract based on OpenZeppelin crowdsale and ERC721 tokens
