### ISSUE TITLE
Storing or generation of repayment values from Terms Contract

### ISSUE THREAD

**Issue by tspoff** [enabledao/enable#66]
* Do we need a big table? How many variants are there?
* Can we have it mathematically derived w/ a few parameters (for less cost)?

If we do need a table, I envision us passing it in on contract creation and having it be static.

**Comment by tspoff** [comment]
Looking at the loan terms we decided, you made it seem super simple.

Idea: There will be a function that users can call to see how much should be repaid at a given time, or now. This will also determine if payments are late or in default.

For Ines Loan:

*Parameters*
Principal: US$60,000
Interest: 6% per annum (i.e. 0.5% monthly)
Grace period on Principal: 24 months
Loan Tenor: 120 months (10 years including 2 years of study)
Results
Grace period installment (1st 2 years): $300
Monthly installment post-graduation: $800
Final repayment tranche: 20 Sept 2029


During the first 24 months of loan, payment is $300 per month.
During the next 96 months of loan, payment is $800 per month.

The start time occurs at the timestamp when the debt transfer officially is transferred on-chain.

If at any point the balance repaid is lower than the expected amount.

So to calculate how much should be repaid at any given time…

monthsPast = simple timestamp calculation w/ start time & now.

If (monthsPast < 24) {
	300 * monthsPast
}

If (monthsPast > 24) {
	300 * 24 + 800 * (monthsPast - 24)
}

The amount each person should be able to get is totalRepaid / userOwernshipPercentages - totalWithdrawnByUser. This assumes no transfer of ownership. Or if users can only transfer their WHOLE ownership stake and not part.

[Dharma has examples of calculating % given that we only have integers]

**Comment by onggunhao** [comment]
@tspoff Agreed - I think the $300 - $800 per month and timestamp calculations works for now for the MVP. 

I like the idea of having the amortization table be dynamically generated - the math is surprisingly simple. It's basically a geometric series summation, which requires the `Math.pow` function. 

Is there a `safemath` equivalent library that does this? I think I've learnt enough solidity to take a crack at this, would love to work on it tomorrow.

### Generation of Amortization Table
One thing we could explore is having a `.call` function that returns the amortization table based on params (i.e. interest, duration, grace period for interest, grace period for principal). T We can adapt existing loan calculator code from existing libraries:

[Dana Cita Loan Library](https://github.com/danacita/loanjs/blob/master/src/repaymentSchedule.ts) (my former company's, which was in turn forked from another library)
[Finance JS](http://financejs.org/)

### Repayments Array
Ines will make repayments through a `repay` function, which will store incoming repayments in a `repayments` array. 

### Calculation of Late Repayments
This can be done through a `call` function that calculates the total repayments due by a certain day / date / time (based on amortization table), and compares it against repayments made in `repayments` array. 

### Withdrawals by Lenders
We should move the discussion of storing of Lender repayments to issue #68.

**Comment by onggunhao** [comment]
So - it's actually implemented in a similar way in Apache Fineract:

Generates a loan schedule dynamically based on parameters
[/AbstractLoanScheduleGenerator](https://github.com/apache/fineract/blob/develop/fineract-provider/src/main/java/org/apache/fineract/portfolio/loanaccount/loanschedule/domain/AbstractLoanScheduleGenerator.java)

Generates a Loan Repayment Schedule based on existing loan params, and made repayments
[AbstractLoanRepaymentScheduleTransactionProcessor](https://github.com/apache/fineract/blob/develop/fineract-provider/src/main/java/org/apache/fineract/portfolio/loanaccount/domain/transactionprocessor/AbstractLoanRepaymentScheduleTransactionProcessor.java)

**Comment by onggunhao** [comment]
### Additional notes and terminology:

Resources:
[Investopedia on Grace Period vs Moratorium](https://www.investopedia.com/ask/answers/111314/whats-difference-between-grace-period-and-moratorium-period.asp)
https://businessjargons.com/moratorium-period.html

**Grace Period**: (i.e. where borrower pays no interest or principal, similar to credit cards which are only settled at the end of the month)

**Moratorium on principal, borrower pays monthly interest**: (i.e. borrower continues to pay interest on outstanding principal)

**Moratorium on principal, monthly interest accumulates**: where the borrower doesn't pay anything during moratorium period, but interest is added on to the balance of loan
Grace Period on Interest and Principal.

**Comment by onggunhao** [comment]
@tspoff @adibas03 I'll be picking up on this issue today + tomorrow. 

I'll be implementing the `ITermsContract -> getExpectedRepaymentValue` method to dynamically calculate expectedRepaymentValue. 

I'll be adding an additional method in `ITermsContract -> getAmortizationTable` which will return an array of 

![image](https://user-images.githubusercontent.com/518024/56459427-1d6f0400-63c6-11e9-8d73-b6762891d642.png)

![image](https://user-images.githubusercontent.com/518024/56459488-f107b780-63c6-11e9-900b-e12a69a704c5.png)

**Comment by onggunhao** [comment]
# High-level spec

> I'll be using this as a scratchpad to think through how to implement the Dai Loan contract from first principles. Will later compare notes with Dharma's implementation.

`crowdloan.sol -> constructor`
Will take in 4 params:
* principal
* tenor (i.e. finance-speak for length of loan contract) 
* `TimeUnitType`
* interest rate per time unit (i.e. matches with `TimeUnitType`)
* interestMoratorium: period of time 
* principalMoratorium:

- [ ] **Design question:** For better UX, should we differentiate between `repaymentPeriod` and `TimeUnitType`?
- [ ] **Design question:** Should we build in different compounding options in V1 of this loan contract?

**Functions**:
`getInterestRatePerAnnum`: calculates the per-annum interest rate

`generateAmortizationTable`: generates the repayment table based on parameters
- [ ] **Design Question:** Should we differentiate between when the loan has been disbursed and not?
- [ ] **Design Question:** Should we generate monthly dates (e.g. 1st May, 1st June, 1st July) using [`ethereum-datetime`](https://github.com/pipermerriam/ethereum-datetime)?

`getExpectedRepaymentValue`: simple function to loop over amortization table, get expected repayment value

`getValueRepaidToDate`: simple function to go over array of existing repayments

**Comment by onggunhao** [comment]
Good calculator that are currently available

https://loanwell.com/repayment-schedule-calculator?step=repaymentSchedule

**Comment by onggunhao** [comment]
Issue moved to https://github.com/enabledao/enable-contracts/issues/18. Closing and moving
