### ISSUE TITLE
Analysis of similar projects

### ISSUE THREAD

**Issue by tspoff** [enabledao/enable#69]
### lendoit
https://lendoit.com/

### colendi
https://www.colendi.com/
Colendi is doing sovereign ID + Credit scoring mechanism as their core product.
**Conclusion**: Core business is possible partner, looking to build competing product in the future

- Credit scores are more credit bureau like - they collect phone / social media data, combine it with data from trusted providers. and Colendi calculates a score based on it. 
- This score is sold to lenders / merchants.
- The first app they want to build is microlending
- Our app would be an app on top of the core mechanic, it’s one of the things they’re looking to build going forward.

Ultimate vision: “In Colendi ecosystem, users can create their Colendi ID and get Colendi Score and can join Colendi network to access microcredits, P2P financing and installment shopping by simply using Colendi app.”

### EthLend
Interesting project for ethereum loans. Talks about support for unsecured loans in the future, they have users earn 'credit tokens' on successful repayments that they can stake as 'reputational collateral' in future loans.
**Conclusion**: Good source of inspiration

### r/borrow
Online P2P loan marketplace. No blockchain, just people! Interesting case study in p2p unsecured lending.
https://www.reddit.com/r/borrow/

**Comment by onggunhao** [comment]
Possible other inspirations as well:

Bitbond
https://www.bitbond.com/

**Comment by onggunhao** [comment]
@tspoff I think it's a good idea for this to be subsumed into #90. I do wonder whether we can get a MBA volunteer to help us out with a lot of the business + market research stuff.
