### ISSUE TITLE
Adapt Crowdsale contract to use Dai ERC-20 token

### ISSUE THREAD

**Issue by onggunhao** [enabledao/enable#70]
Some previous discussion:

Reddit discussion on Dai crowdsale contract:
https://www.reddit.com/r/ethdev/comments/8iith6/what_would_a_crowdsale_raise_in_dai_look_like/

BlankDAO evidently did a crowdsale using Dai:
https://github.com/BlankDAO/smart-contracts/blob/master/contracts/BlankCrowdsale.sol

**Comment by tspoff** [comment]
Nice find. Looks clean. 

So it...
* Has a whitelist (the ‘referrers’)
* Has math for calculating dollar values
* Trades DAI for BlankToken, which would be the debt token

**Comment by onggunhao** [comment]
Closed
