### ISSUE TITLE
Implement multiple payment methods (Wyre, Kyber)

### ISSUE THREAD

**Issue by tspoff** [enabledao/enable#71]
### Idea: Easy Crypto -> Stablecoins in-dapp
- We can integrate Kyber network to have an in-dapp token converter such that lenders can convert Eth or ERC-20s into stablecoins using Kyber DEX.
- I believe Airswap or 0x could offer similar functionality

### Idea: Fiat -> Crypto onboarding
- We could speak w/ Wyre protocol ("API for compilance and payments") about them handling KYC and fiat onramping for the product.

**Comment by onggunhao** [comment]
@tspoff I'd personally love both these options. Kyber would be fantastic, I've been hoping to work with their developer API

**Comment by onggunhao** [comment]
@tspoff Let me look into Wyre and update the wireframes. I think it's an interesting way to onboard non-crypto lenders.

Only question: what would be their repayment address? (i.e. who would the debt token be given to?)

**Comment by onggunhao** [comment]
@tspoff I've renamed task to its actionable and moved it into backlog

**Comment by onggunhao** [comment]
Moved to https://github.com/enabledao/enable-contracts/issues/29
