### ISSUE TITLE
Duplicate Enable repo to create enable-contracts repo

### ISSUE THREAD

**Issue by adibas03** [enabledao/enable#82]
To separate the Front end from the smart contract,
the contracts progress will be moved to a new repo https://github.com/enabledao/enable-contracts

**Comment by onggunhao** [comment]
@adibas03 For my own understanding, what is the convention in the Eth community?

i.e. Is the convention to have a main repo, that pulls in individual smart contract repos (through Lerna or just Git submodules) for compilation + deployment during CI / CD?

**Comment by adibas03** [comment]
Actually, most of the time, the UI only need the contracts json, or abi, and need not be submodules,
although for smaller projects, it does not matter as the total file size is smaller.
The contract repo can be imported as an npm package (using github https url) into the main project, and the necessary components used

**Comment by onggunhao** [comment]
Thanks! Closing this issue as @tspoff completed it
