### ISSUE TITLE
Setup A/B testing conversion funnels and metrics for Enable.credit

### ISSUE THREAD

**Issue by onggunhao** [enabledao/enable#91]
**Landing page**
- [x] Create unbounce landing page (1st variant)
- [x] Setup Mailchimp for email capture
- [x] DNS settings for enable.credit
- [x] Setup Google Analytics, Facebook Pixel
- [x] Setup OG image for landing page
- [x] Setup GA and FB Pixel conversion events and goal funnel
- [x] Mailchimp to Discord notification
- [ ] Create 2nd variant of landing page

**Comment by wimanesti** [comment]
I can't access google analytics, totally blank:
![image](https://user-images.githubusercontent.com/49892791/59808997-f632a580-9328-11e9-9110-25e59f2f4790.png)

**Comment by onggunhao** [comment]
> I can't access google analytics, totally blank:
> ![image](https://user-images.githubusercontent.com/49892791/59808997-f632a580-9328-11e9-9110-25e59f2f4790.png)

@wimanesti Hmm you probably need to clear your browser cache. Can you try again in an Incognito browser? 

If it works in Incognito, you'll then need to clear cache and hard reload. See this article
https://www.getfilecloud.com/blog/2015/03/tech-tip-how-to-do-hard-refresh-in-browsers/

**Comment by onggunhao** [comment]
Completed. We can iterate on the enable.credit page as we go along
