### ISSUE TITLE
Prepare ines.fund fundraiser writeup and video

### ISSUE THREAD

**Issue by onggunhao** [enabledao/enable#96]
# Task
@wimanesti As spoken, we need to prepare the fundraising materials for www.ines.fund. This consists of the 
* Writeup (i.e. introduce yourself, why you are hoping to go to Cornell)
* Video introduction

You're going to represent yourself for this loan. From the perspective of having had to fundraise before (and knowing you well), I do have a few suggestions for things you can put into the writeup:

**Trust**
1. How do I know that you are a real person?
2. How do I know that you're actually going to use the money for Cornell?
3. How do I know that you're not a scammer who will run away with the money?

**Underwriting-focus**
1. How can you convince me that you will repay?
2. What is the average graduation salary from Cornell?
3. How sure are you that you will be able to find a job or visa in the US?
4. What happens if you can't get a job in the US post-graduation?
5. Will you be working part-time as a student?
6. What other incomes are there to support loan payments? What is the rough debt burden ratio?

**Social-impact**
1. Why you want to study at Cornell
2. Your background having lead HR at 2 major Indonesian companies
3. How do you intend to use the platform you have at Cornell to push certain things forward?
4. What does it mean to be an Indonesian having the opportunity at Cornell?

# Things you will need to be familiar with

1. Balsamiq wireframes at https://bit.ly/enable-draft-4 for roughly what the loan factsheet looks like

# Possible inspirations

1. Kickstarter (mostly art + hardware)
2. GoFundMe (see the education section)
3. Kiva (see education loans)

The important nuance for each platform is:
1. **Kickstarter**: people are basically "buying" products here. But we can still learn from their high-quality writeups, video production
2. **GoFundMe**: these are donation oriented. But we can still learn from successful writeups
3. **Kiva**: most Kiva loans are small ticket "commodity" loans, that don't have the emotional depth that Kickstarter.

What does a Kickstarter-quality GoFundMe look like?

**Comment by wimanesti** [comment]
Some inspirations (initial skimming, to be reviewed further):
https://www.indiegogo.com/projects/earth-ar-and-ai-enabled-model-of-planet-earth#/
https://www.kiva.org/lend/1764967
https://www.indiegogo.com/projects/parq-app-parking-without-a-question#/
https://www.kiva.org/about/how
https://www.kickstarter.com/projects/winstonprivacy/winston-the-worlds-most-advanced-online-privacy-device/description
https://www.kickstarter.com/projects/gabrielwyner/fluent-forever-the-app-learn-to-think-in-any-langu?ref=discovery_category_most_funded

**Comment by onggunhao** [comment]
@wimanesti Cool! Let us know when you're ready - will leave this in your capable hands

**Comment by wimanesti** [comment]
GoFundMe page draft:
https://docs.google.com/document/d/14sTWvKMKDiFPp1ey5SgQddiA-hda0EbJiqigFE7QJAE/edit?usp=sharing

**Comment by wimanesti** [comment]
www.ines.fund - draft on progress
https://docs.google.com/document/d/1xBrQST6q4c0Oq_rnVM7buKgM7PTmh6qCW6X1jIk6wPc/edit?usp=sharing

**Comment by wimanesti** [comment]
Video references:
https://www.kickstarter.com/projects/872898516/art-prof-visual-art-essentials?ref=discovery_category&term=education
https://www.kickstarter.com/projects/1438648563/art-education-for-rural-kids-send-me-to-hanksville?ref=discovery_category&term=education
https://www.kickstarter.com/projects/1199281917/a-different-mirror-an-exhibition-on-body-image?ref=discovery_category&term=education
https://www.kickstarter.com/projects/688443917/fiddlehead-play-collective-a-play-and-co-working-s-0?ref=discovery_category&term=education


Outline story:
- Introduction
- My credentials and work experience
- Why I need 60k and how am I going to repay (animasi/kolase)
- Convince them that it's an investment
- What it means to me and how I pay it forward (think carefully)
- What people say about me (testi, either showing written reference or video)

**Comment by nczhu** [comment]
I can help with feedback on this. Please send me video draft when you have it.
